# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 2, 3, 17, 33, 48, 148845, tzinfo=utc))),
            ],
        ),
    ]
