# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
