# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0002_auto_20170203_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInputSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=3)),
                ('percent_emerging', models.IntegerField(default=0.6)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcf.Scenario')),
            ],
        ),
    ]
