# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0005_auto_20170204_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
            ],
        ),
        migrations.CreateModel(
            name='InputSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyYearData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=200)),
                ('strike_price', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('min_levelised_cost', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('max_levelised_cost', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('project_size', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('max_deployment', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcf.AuctionYear')),
            ],
        ),
        migrations.AddField(
            model_name='auctionyear',
            name='inputset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcf.InputSet'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='inputset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcf.InputSet'),
        ),
    ]
