# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0006_auto_20170204_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologyyeardata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcf.TechnologyYearData')),
            ],
        ),
        migrations.RenameModel(
            old_name='InputSet',
            new_name='AuctionYearSet',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='inputset',
            new_name='auctionyearset',
        ),
    ]
