# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0007_auto_20170204_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelised_cost', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('affordable', models.BooleanField(default=False)),
                ('successful', models.BooleanField(default=False)),
                ('technologyyeardata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcf.TechnologyYearData')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectset',
            name='technologyyeardata',
        ),
        migrations.DeleteModel(
            name='ProjectSet',
        ),
    ]
