# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0008_auto_20170204_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='generalinputset',
        ),
        migrations.AddField(
            model_name='scenario',
            name='budget',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name='scenario',
            name='percent_emerging',
            field=models.DecimalField(decimal_places=3, default=0.6, max_digits=4),
        ),
        migrations.DeleteModel(
            name='GeneralInputSet',
        ),
    ]
