# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0010_auto_20170205_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionyear',
            old_name='inputset',
            new_name='scenario',
        ),
    ]
