# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0011_auto_20170206_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionyear',
            name='wholesale_price',
            field=models.IntegerField(default=50),
        ),
    ]
