# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0012_auctionyear_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionyeartechnology',
            name='pot',
            field=models.CharField(choices=[('E', 'Emerging'), ('M', 'Mature')], default='E', max_length=1),
        ),
    ]
