# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0013_auctionyeartechnology_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionyeartechnology',
            name='year',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='lcf.AuctionYear'),
        ),
    ]
