# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0016_auto_20170207_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionyeartechnology',
            name='load_factor',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
