# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0019_auto_20170208_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionyeartechnology',
            old_name='max_deployment',
            new_name='max_deployment_cap',
        ),
        migrations.RenameField(
            model_name='auctionyeartechnology',
            old_name='project_size',
            new_name='project_gen',
        ),
        migrations.AlterField(
            model_name='auctionyear',
            name='wholesale_price',
            field=models.IntegerField(default=53),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=3.3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='percent_emerging',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
        ),
    ]
