# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0020_auto_20170208_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
