# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0021_scenario_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionyear',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lcf.Scenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='budget',
            field=models.FloatField(default=3.3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='percent_emerging',
            field=models.FloatField(default=0.6),
        ),
    ]
