# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0022_auto_20170208_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionyear',
            name='pot',
            field=models.CharField(choices=[('E', 'Emerging'), ('M', 'Mature'), ('NW', 'Negawatts'), ('SN', 'Separate negotiations')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='auctionyeartechnology',
            name='pot',
            field=models.CharField(choices=[('E', 'Emerging'), ('M', 'Mature'), ('NW', 'Negawatts'), ('SN', 'Separate negotiations')], default='E', max_length=1),
        ),
    ]
