# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0023_auto_20170210_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E', 'Emerging'), ('M', 'Mature'), ('NW', 'Negawatts'), ('SN', 'Separate negotiations')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OFW', 'Offshore wind'), ('ONW', 'Onshore wind'), ('NU', 'Nuclear'), ('TL', 'Tidal lagoon'), ('TS', 'Tidal stream'), ('WA', 'Wave'), ('PVLS', 'Solar PV')], default='OFW', max_length=4)),
                ('min_levelised_cost', models.FloatField(default=100)),
                ('max_levelised_cost', models.FloatField(default=100)),
                ('strike_price', models.FloatField(default=100)),
                ('load_factor', models.FloatField(default=0.5)),
                ('project_gen', models.FloatField(default=100)),
                ('max_deployment_cap', models.FloatField(default=100)),
                ('pot', models.ForeignKey(default='E', on_delete=django.db.models.deletion.CASCADE, to='lcf.Pot')),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionyeartechnology',
            name='year',
        ),
        migrations.RemoveField(
            model_name='auctionyear',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='storedproject',
            name='auction_year_technology',
        ),
        migrations.DeleteModel(
            name='AuctionYearTechnology',
        ),
        migrations.AddField(
            model_name='pot',
            name='auctionyear',
            field=models.ForeignKey(default=232, on_delete=django.db.models.deletion.CASCADE, to='lcf.AuctionYear'),
        ),
        migrations.AddField(
            model_name='storedproject',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcf.Technology'),
        ),
    ]
