# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0024_auto_20170210_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pot',
            unique_together=set([('auctionyear', 'name')]),
        ),
    ]
