# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0025_auto_20170210_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pot',
            unique_together=set([]),
        ),
    ]
