# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0027_auto_20170211_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='rank_by_strike_price',
            new_name='rank_by_levelised_cost',
        ),
    ]
