# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0028_auto_20170212_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionyear',
            name='gas_price',
            field=models.IntegerField(default=85),
        ),
    ]
