# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0029_auctionyear_gas_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='project_gen',
        ),
        migrations.AddField(
            model_name='technology',
            name='project_gen_incorrect',
            field=models.FloatField(default=100, verbose_name='Average project generation'),
        ),
    ]
