# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0030_auto_20170213_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='cum_project_gen_incorrect',
            field=models.FloatField(default=1000, verbose_name='Cumulative project generation'),
        ),
    ]
