# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0031_technology_cum_project_gen_incorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='set_strike_price',
            field=models.BooleanField(default=False, verbose_name='Generate strike price ourselves?'),
        ),
    ]
