# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0033_remove_technology_cum_project_gen_incorrect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='project_gen_incorrect',
            new_name='project_gen',
        ),
    ]
