# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0034_auto_20170221_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedproject',
            name='technology',
        ),
        migrations.DeleteModel(
            name='StoredProject',
        ),
    ]
