# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0035_auto_20170221_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionyear',
            name='gas_price',
            field=models.FloatField(default=85),
        ),
        migrations.AlterField(
            model_name='auctionyear',
            name='wholesale_price',
            field=models.FloatField(default=53),
        ),
    ]
