# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0036_auto_20170222_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='end_year',
            field=models.IntegerField(default=2026),
        ),
    ]
