# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0038_scenario_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='excel_wp_error',
            field=models.BooleanField(default=True, verbose_name='Include the Excel error in the emerging pot wholesale price?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='end_year',
            field=models.IntegerField(default=2025),
        ),
    ]
