# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0039_auto_20170305_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('E', 'Emerging'), ('M', 'Mature'), ('FIT', 'Feed-in-tariff'), ('SN', 'Separate negotiations')], default='E', max_length=1),
        ),
    ]
