# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0040_auto_20170315_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='tidal_levelised_cost_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('E', 'Emerging'), ('M', 'Mature'), ('FIT', 'Feed-in-tariff'), ('SN', 'Separate negotiations')], default='E', max_length=3),
        ),
    ]
