# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0041_auto_20170315_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='tidal_levelised_cost_distribution',
        ),
        migrations.AddField(
            model_name='scenario',
            name='tidal_levelised_cost_distribution',
            field=models.BooleanField(default=False),
        ),
    ]
