# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0043_technology_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='excel_2020_gen_error',
            field=models.BooleanField(default=True, verbose_name='Include the Excel error that counts cumulative generation from 2020 for auction and negotiations (but not FIT)'),
        ),
    ]
