# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0045_auto_20170317_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='excel_nw_carry_error',
            field=models.BooleanField(default=True, verbose_name="Include the Excel error that carries FIT into next year, even though it's been spent"),
        ),
    ]
