# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0046_scenario_excel_nw_carry_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='excel_nw_carry_error',
            field=models.BooleanField(default=True, verbose_name="Include the Excel error that carries NWFIT into next year, even though it's been spent"),
        ),
    ]
