# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0047_auto_20170317_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='awarded_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='awarded_gen',
            field=models.FloatField(default=0),
        ),
    ]
