# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0049_auto_20170317_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='auction_has_run',
            field=models.BooleanField(default=False),
        ),
    ]
