# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0050_pot_auction_has_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionyear',
            name='budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
