# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0052_auto_20170322_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionyear',
            name='budget',
        ),
    ]
