# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0053_remove_auctionyear_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='end_year',
            new_name='end_year1',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='start_year',
            new_name='start_year1',
        ),
        migrations.AddField(
            model_name='scenario',
            name='end_year2',
            field=models.IntegerField(default=2030),
        ),
        migrations.AddField(
            model_name='scenario',
            name='start_year2',
            field=models.IntegerField(default=2026),
        ),
    ]
