# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0054_auto_20170326_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='budget2',
            field=models.FloatField(default=3.3, verbose_name='Budget period 2 (£bn)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='budget',
            field=models.FloatField(default=3.3, verbose_name='Budget period 1 (£bn)'),
        ),
    ]
