# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0056_auto_20170328_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='budget2',
            field=models.FloatField(blank=True, null=True, verbose_name='Budget period 2 (£bn) - leave blank to use same as period 1'),
        ),
    ]
