# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0057_auto_20170328_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='excel_wp_error',
        ),
        migrations.AddField(
            model_name='scenario',
            name='excel_sp_error',
            field=models.BooleanField(default=True, verbose_name='Include the Excel error in the emerging pot strike price?'),
        ),
    ]
