# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0058_auto_20170328_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='num_projects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
