# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0059_technology_num_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='num_projects',
            new_name='num_new_projects',
        ),
        migrations.AlterField(
            model_name='technology',
            name='max_deployment_cap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
