# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0062_auctionyear_budget_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='awarded_cost_result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='awarded_gen_result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
