# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0065_pot_auction_budget_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='cum_owed_v_absolute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='cum_owed_v_gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='cum_owed_v_wp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
