# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0067_pot_previously_funded_projects_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='excel_quirks',
            field=models.BooleanField(default=True, verbose_name='Include all Excel quirks'),
        ),
    ]
