# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0068_scenario_excel_quirks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='excel_2020_gen_error',
            field=models.BooleanField(default=False, verbose_name='Include the Excel error that counts cumulative generation from 2020 for auction and negotiations (but not FIT)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_nw_carry_error',
            field=models.BooleanField(default=False, verbose_name="Include the Excel error that carries NWFIT into next year, even though it's been spent"),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_sp_error',
            field=models.BooleanField(default=False, verbose_name='Include the Excel error in the emerging pot strike price?'),
        ),
    ]
