# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0071_auto_20170403_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='cum_awarded_gen_result',
            field=models.FloatField(blank=True, null=True, verbose_name='Cumulative generation (TWh)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='awarded_gen',
            field=models.FloatField(blank=True, null=True, verbose_name='Generation awarded each year (TWh)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('OFW', 'Offshore wind'), ('ONW', 'Onshore wind'), ('NU', 'Nuclear'), ('TL', 'Tidal lagoon'), ('TS', 'Tidal stream'), ('WA', 'Wave'), ('PVLS', 'Solar PV'), ('NW', 'Negawatts')], default='OFW', max_length=4),
        ),
    ]
