# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0073_technology_cum_owed_v_wp'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='cum_owed_v_gas',
            field=models.FloatField(default=0, verbose_name='Cost v gas (£bn)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='cum_owed_v_wp',
            field=models.FloatField(default=0, verbose_name='Accounting cost (£bn)'),
        ),
    ]
