# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0074_auto_20170404_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='cum_awarded_gen',
            field=models.FloatField(default=0, verbose_name='Cumulative new generation (TWh)'),
        ),
    ]
