# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0075_technology_cum_awarded_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='cum_owed_v_absolute',
            field=models.FloatField(default=0, verbose_name='Absolute cost (£bn)'),
        ),
    ]
