# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0076_technology_cum_owed_v_absolute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionyear',
            name='budget_result',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='auction_budget_result',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='auction_has_run',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='auction_results',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='awarded_cost_result',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='awarded_gen_result',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='budget_result',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='cum_awarded_gen_result',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='cum_owed_v_absolute',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='cum_owed_v_gas',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='cum_owed_v_wp',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='previously_funded_projects_results',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='rank_by_levelised_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='awarded_cost',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='awarded_gen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cum_awarded_gen',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cum_owed_v_absolute',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cum_owed_v_gas',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cum_owed_v_wp',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='num_new_projects',
        ),
    ]
