# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0077_auto_20170404_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='num_new_projects',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
