# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0081_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='effects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
