# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0083_scenario_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='policies',
            field=models.ManyToManyField(blank=True, to='lcf.Policy'),
        ),
    ]
