# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0085_auto_20170412_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='end_year1',
            field=models.IntegerField(default=2025, verbose_name='End of period 1'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='percent_emerging',
            field=models.FloatField(default=0.6, verbose_name='Percentage in emerging pot'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='subsidy_free_p2',
            field=models.BooleanField(default=False, verbose_name='Only subsidy-free CFDs for period 2'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('OFW', 'Offshore wind'), ('ONW', 'Onshore wind'), ('TS', 'Tidal stream'), ('NW', 'Negawatts'), ('WA', 'Wave'), ('TL', 'Tidal lagoon'), ('NU', 'Nuclear'), ('PVLS', 'Solar PV')], default='OFW', max_length=4),
        ),
    ]
