# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0087_auto_20170420_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('FIT', 'Feed-in-tariff'), ('E', 'Emerging'), ('SN', 'Separate negotiations'), ('M', 'Mature')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_cum_project_distr',
            field=models.BooleanField(default=False, verbose_name='Include the Excel quirk that calculates number of projects cumulatively and then excludes previously successful ones (as opposed to just treating each year separately)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('WA', 'Wave'), ('NW', 'Negawatts'), ('TL', 'Tidal lagoon'), ('ONW', 'Onshore wind'), ('NU', 'Nuclear'), ('OFW', 'Offshore wind'), ('TS', 'Tidal stream'), ('PVLS', 'Solar PV')], default='OFW', max_length=4),
        ),
    ]
