# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0088_auto_20170502_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='excel_cum_project_distr',
        ),
        migrations.AddField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_all',
            field=models.BooleanField(default=False, verbose_name='Include the Excel quirk that allows all previously unsuccessful projects to bid in future auctions'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_nuclear',
            field=models.BooleanField(default=False, verbose_name='Allows unsuccessful nuclear projects to be considered in future auctions (but not other technologies)'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('SN', 'Separate negotiations'), ('M', 'Mature'), ('E', 'Emerging'), ('FIT', 'Feed-in-tariff')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_quirks',
            field=models.BooleanField(default=True, verbose_name='Include all Excel quirks (if selected, overrides individual quirk settings)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NW', 'Negawatts'), ('NU', 'Nuclear'), ('PVLS', 'Solar PV'), ('WA', 'Wave'), ('TS', 'Tidal stream'), ('ONW', 'Onshore wind'), ('TL', 'Tidal lagoon'), ('OFW', 'Offshore wind')], default='OFW', max_length=4),
        ),
    ]
