# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0089_auto_20170503_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('E', 'Emerging'), ('SN', 'Separate negotiations'), ('M', 'Mature'), ('FIT', 'Feed-in-tariff')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_2020_gen_error',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: count cumulative generation from 2020 for auction and negotiations (but not FIT)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_all',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: allow previously unsuccessful projects for all technologies to be considered in future years (overrides maximum deployment limit)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_nuclear',
            field=models.BooleanField(default=True, verbose_name='Excel quirk: allow previously unsuccessful nuclear projects to be considered in future years'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_nw_carry_error',
            field=models.BooleanField(default=False, verbose_name="Excel quirk: carry NWFIT into next year, even though it's been spent"),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_quirks',
            field=models.BooleanField(default=False, verbose_name='Include all Excel quirks (if selected, overrides individual quirk settings)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_sp_error',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: use future strike price rather than year contract agreed'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NW', 'Negawatts'), ('NU', 'Nuclear'), ('OFW', 'Offshore wind'), ('TS', 'Tidal stream'), ('PVLS', 'Solar PV'), ('TL', 'Tidal lagoon'), ('WA', 'Wave'), ('ONW', 'Onshore wind')], default='OFW', max_length=4),
        ),
    ]
