# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0090_auto_20170503_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='method',
            field=models.CharField(choices=[('MU', 'multiply'), ('SU', 'subtract')], default='MU', max_length=2),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('FIT', 'Feed-in-tariff'), ('E', 'Emerging'), ('M', 'Mature'), ('SN', 'Separate negotiations')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('OFW', 'Offshore wind'), ('TS', 'Tidal stream'), ('TL', 'Tidal lagoon'), ('NW', 'Negawatts'), ('WA', 'Wave'), ('NU', 'Nuclear'), ('ONW', 'Onshore wind'), ('PVLS', 'Solar PV')], default='OFW', max_length=4),
        ),
    ]
