# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0091_auto_20170503_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='load_factor_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='max_deployment_cap_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='max_levelised_cost_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='min_levelised_cost_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='num_new_projects_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='project_gen_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='strike_price_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='method',
            field=models.CharField(choices=[('SU', 'subtract'), ('MU', 'multiply')], default='SU', max_length=2),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('M', 'Mature'), ('FIT', 'Feed-in-tariff'), ('SN', 'Separate negotiations'), ('E', 'Emerging')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('TL', 'Tidal lagoon'), ('ONW', 'Onshore wind'), ('OFW', 'Offshore wind'), ('WA', 'Wave'), ('TS', 'Tidal stream'), ('NU', 'Nuclear'), ('NW', 'Negawatts'), ('PVLS', 'Solar PV')], default='OFW', max_length=4),
        ),
    ]
