# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0092_auto_20170506_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='csv_inc_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('FIT', 'Feed-in-tariff'), ('E', 'Emerging'), ('M', 'Mature'), ('SN', 'Separate negotiations')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NW', 'Negawatts'), ('PVLS', 'Solar PV'), ('TS', 'Tidal stream'), ('ONW', 'Onshore wind'), ('NU', 'Nuclear'), ('TL', 'Tidal lagoon'), ('WA', 'Wave'), ('OFW', 'Offshore wind')], default='OFW', max_length=4),
        ),
    ]
