# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0094_auto_20170506_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('M', 'Mature'), ('FIT', 'Feed-in-tariff'), ('SN', 'Separate negotiations'), ('E', 'Emerging')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('PVLS', 'Solar PV'), ('WA', 'Wave'), ('TL', 'Tidal lagoon'), ('ONW', 'Onshore wind'), ('NU', 'Nuclear'), ('TS', 'Tidal stream'), ('OFW', 'Offshore wind'), ('NW', 'Negawatts')], default='OFW', max_length=4),
        ),
    ]
