# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0095_auto_20170508_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('M', 'Mature'), ('SN', 'Separate negotiations'), ('FIT', 'Feed-in-tariff'), ('E', 'Emerging')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('OFW', 'Offshore wind'), ('TS', 'Tidal stream'), ('TL', 'Tidal lagoon'), ('NW', 'Negawatts'), ('ONW', 'Onshore wind'), ('PVLS', 'Solar PV'), ('WA', 'Wave'), ('NU', 'Nuclear')], default='OFW', max_length=4),
        ),
    ]
