# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0096_auto_20170508_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('SN', 'Separate negotiations'), ('M', 'Mature'), ('FIT', 'Feed-in-tariff'), ('E', 'Emerging')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NW', 'Negawatts'), ('TL', 'Tidal lagoon'), ('OFW', 'Offshore wind'), ('TS', 'Tidal stream'), ('NU', 'Nuclear'), ('ONW', 'Onshore wind'), ('PVLS', 'Solar PV'), ('WA', 'Wave')], default='OFW', max_length=4),
        ),
    ]
