# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0097_auto_20170509_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('SN', 'Separate negotiations'), ('M', 'Mature'), ('E', 'Emerging'), ('FIT', 'Feed-in-tariff')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('TS', 'Tidal stream'), ('NW', 'Negawatts'), ('WA', 'Wave'), ('TL', 'Tidal lagoon'), ('NU', 'Nuclear'), ('PVLS', 'Solar PV'), ('ONW', 'Onshore wind'), ('OFW', 'Offshore wind')], default='OFW', max_length=4),
        ),
    ]
