# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0098_auto_20170509_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='prices_inc_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('M', 'Mature'), ('E', 'Emerging'), ('FIT', 'Feed-in-tariff'), ('SN', 'Separate negotiations')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_2020_gen_error',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: count cumulative generation from 2020 for auction and negotiations'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_all',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: allow previously unsuccessful projects for all technologies to be considered in future years (overrides maximum deployment limit). Incompatible with switching technologies on/off for individual years.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_nuclear',
            field=models.BooleanField(default=True, verbose_name='Excel quirk: allow previously unsuccessful projects in separate negotiations to be considered in future years'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_nw_carry_error',
            field=models.BooleanField(default=False, verbose_name="Excel quirk: carry NWFIT budget into next year, even though it's been spent"),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NU', 'Nuclear'), ('TS', 'Tidal stream'), ('TL', 'Tidal lagoon'), ('NW', 'Negawatts'), ('ONW', 'Onshore wind'), ('WA', 'Wave'), ('OFW', 'Offshore wind'), ('PVLS', 'Solar PV')], default='OFW', max_length=4),
        ),
    ]
