# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0099_auto_20170512_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='excel_exongenous_clearing_price',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: take clearing price as exogenous input rather than calculating as a result of auction'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('SN', 'Separate negotiations'), ('E', 'Emerging'), ('FIT', 'Feed-in-tariff'), ('M', 'Mature')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_2020_gen_error',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: count cumulative generation from 2020 but cumulative costs from 2021'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_include_previous_unsuccessful_all',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: allow previously unsuccessful projects for ALL technologies to be considered in future years'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_nw_carry_error',
            field=models.BooleanField(default=False, verbose_name="Excel quirk: add an extra £89m to the budget each year, forgetting it's been spent on the previous year's negawatts FIT"),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_quirks',
            field=models.BooleanField(default=False, verbose_name='Include all Excel quirks'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='percent_emerging',
            field=models.FloatField(default=0.6, verbose_name='Proportion in emerging pot'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NW', 'Negawatts'), ('OFW', 'Offshore wind'), ('WA', 'Wave'), ('PVLS', 'Solar PV'), ('NU', 'Nuclear'), ('ONW', 'Onshore wind'), ('TS', 'Tidal stream'), ('TL', 'Tidal lagoon')], default='OFW', max_length=4),
        ),
    ]
