# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0100_auto_20170621_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('FIT', 'Feed-in-tariff'), ('M', 'Mature'), ('SN', 'Separate negotiations'), ('E', 'Emerging')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('TL', 'Tidal lagoon'), ('NW', 'Negawatts'), ('NU', 'Nuclear'), ('PVLS', 'Solar PV'), ('WA', 'Wave'), ('TS', 'Tidal stream'), ('OFW', 'Offshore wind'), ('ONW', 'Onshore wind')], default='OFW', max_length=4),
        ),
    ]
