# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0103_auto_20170624_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='intermediate_budget_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('E', 'Emerging'), ('FIT', 'Feed-in-tariff'), ('M', 'Mature'), ('SN', 'Separate negotiations')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='excel_exongenous_clearing_price',
            field=models.BooleanField(default=False, verbose_name='Excel quirk: take clearing price as external input rather than calculating ourselves'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('NU', 'Nuclear'), ('WA', 'Wave'), ('PVLS', 'Solar PV'), ('NW', 'Negawatts'), ('TS', 'Tidal stream'), ('TL', 'Tidal lagoon'), ('OFW', 'Offshore wind'), ('ONW', 'Onshore wind')], default='OFW', max_length=4),
        ),
    ]
