# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcf', '0104_auto_20170625_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='excel_exongenous_clearing_price',
            new_name='excel_external_clearing_price',
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(choices=[('M', 'Mature'), ('E', 'Emerging'), ('SN', 'Separate negotiations'), ('FIT', 'Feed-in-tariff')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('OFW', 'Offshore wind'), ('ONW', 'Onshore wind'), ('TS', 'Tidal stream'), ('TL', 'Tidal lagoon'), ('PVLS', 'Solar PV'), ('NW', 'Negawatts'), ('NU', 'Nuclear'), ('WA', 'Wave')], default='OFW', max_length=4),
        ),
    ]
