1,'awarded_cap': 'Capacity awarded each year LCF 1 (GW)'))
2,'awarded_cap': 'Capacity awarded each year LCF 2 (GW)'))
1,'awarded_gen': 'Generation awarded each year LCF 1 (TWh)'))
2,'awarded_gen': 'Generation awarded each year LCF 2 (TWh)'))
1,'cum_owed_v_wp','Accounting cost LCF 1 (£bn)'))
2,'cum_owed_v_wp','Accounting cost LCF 2 (£bn)'))
1,'cum_owed_v_gas': 'Cost v gas LCF 1 (£bn)'))
2,'cum_owed_v_gas': 'Cost v gas LCF 2 (£bn)'))
1,'cum_owed_v_absolute': 'Absolute cost LCF 1 (£bn)'))
2,'cum_owed_v_absolute': 'Absolute cost LCF 2 (£bn)'))
1,'cum_awarded_gen': 'Cumulative new generation LCF 1 (TWh)'))
2,'cum_awarded_gen': 'Cumulative new generation LCF 2 (TWh)'))
